<?php

namespace ContainerX8ugl7R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddContactTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddContactType' shared autowired service.
     *
     * @return \App\Form\AddContactType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddContactType.php';

        return $container->privates['App\\Form\\AddContactType'] = new \App\Form\AddContactType();
    }
}
