<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z7i5sjzService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Z7i5sjz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z7i5sjz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mission' => ['privates', '.errored..service_locator.Z7i5sjz.App\\Entity\\Missions', NULL, 'Cannot autowire service ".service_locator.Z7i5sjz": it references class "App\\Entity\\Missions" but no such service exists.'],
        ], [
            'mission' => 'App\\Entity\\Missions',
        ]);
    }
}
