<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X3NNYiJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.X3NNYiJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X3NNYiJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agent' => ['privates', '.errored..service_locator.X3NNYiJ.App\\Entity\\Agents', NULL, 'Cannot autowire service ".service_locator.X3NNYiJ": it references class "App\\Entity\\Agents" but no such service exists.'],
        ], [
            'agent' => 'App\\Entity\\Agents',
        ]);
    }
}
