<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.X3NNYiJ.App\Entity\Agents' shared service.
     *
     * @return \App\Entity\Agents
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.X3NNYiJ": it references class "App\\Entity\\Agents" but no such service exists.');
    }
}
