<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AgentsRepository' shared autowired service.
     *
     * @return \App\Repository\AgentsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AgentsRepository'] = new \App\Repository\AgentsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
