<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddSkillTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AddSkillType' shared autowired service.
     *
     * @return \App\Form\AddSkillType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AddSkillType'] = new \App\Form\AddSkillType();
    }
}
