<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContactsRepository' shared autowired service.
     *
     * @return \App\Repository\ContactsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContactsRepository'] = new \App\Repository\ContactsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
