<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHideoutsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HideoutsRepository' shared autowired service.
     *
     * @return \App\Repository\HideoutsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HideoutsRepository'] = new \App\Repository\HideoutsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
