<?php

namespace ContainerRHju0rH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTargetsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TargetsRepository' shared autowired service.
     *
     * @return \App\Repository\TargetsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TargetsRepository'] = new \App\Repository\TargetsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
