<?php

namespace ContainerElpNopz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QqrmxZxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qqrmxZx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qqrmxZx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agentsRepository' => ['privates', 'App\\Repository\\AgentsRepository', 'getAgentsRepositoryService', true],
        ], [
            'agentsRepository' => 'App\\Repository\\AgentsRepository',
        ]);
    }
}
