<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLqF0ThV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLqF0ThV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLqF0ThV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLqF0ThV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLqF0ThV\App_KernelDevDebugContainer([
    'container.build_hash' => 'LqF0ThV',
    'container.build_id' => '9b4d3875',
    'container.build_time' => 1616153442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLqF0ThV');
