<?php

namespace Container2Y1lBL8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SURtgnnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sURtgnn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sURtgnn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'targetsRepository' => ['privates', 'App\\Repository\\TargetsRepository', 'getTargetsRepositoryService', true],
        ], [
            'targetsRepository' => 'App\\Repository\\TargetsRepository',
        ]);
    }
}
