<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRHju0rH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRHju0rH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRHju0rH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRHju0rH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRHju0rH\App_KernelProdContainer([
    'container.build_hash' => 'RHju0rH',
    'container.build_id' => '198ea6e1',
    'container.build_time' => 1616580384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRHju0rH');
