<?php

namespace ContainerE8N1t6u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddSkillTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddSkillType' shared autowired service.
     *
     * @return \App\Form\AddSkillType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddSkillType.php';

        return $container->privates['App\\Form\\AddSkillType'] = new \App\Form\AddSkillType();
    }
}
