<?php

namespace ContainerLfcmcCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_18TYlwJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.18TYlwJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.18TYlwJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hideoutsRepository' => ['privates', 'App\\Repository\\HideoutsRepository', 'getHideoutsRepositoryService', true],
        ], [
            'hideoutsRepository' => 'App\\Repository\\HideoutsRepository',
        ]);
    }
}
