<?php

namespace ContainerLfcmcCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7l_0eYIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7l.0eYI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7l.0eYI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'missionsRepository' => ['privates', 'App\\Repository\\MissionsRepository', 'getMissionsRepositoryService', true],
        ], [
            'missionsRepository' => 'App\\Repository\\MissionsRepository',
        ]);
    }
}
