<?php

namespace ContainerLfcmcCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddAgentFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddAgentFormType' shared autowired service.
     *
     * @return \App\Form\AddAgentFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddAgentFormType.php';

        return $container->privates['App\\Form\\AddAgentFormType'] = new \App\Form\AddAgentFormType();
    }
}
