<?php

namespace ContainerYeDyDBp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bk4moDuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bk4moDu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bk4moDu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hideout' => ['privates', '.errored..service_locator.Bk4moDu.App\\Entity\\Hideouts', NULL, 'Cannot autowire service ".service_locator.Bk4moDu": it references class "App\\Entity\\Hideouts" but no such service exists.'],
        ], [
            'hideout' => 'App\\Entity\\Hideouts',
        ]);
    }
}
