<?php

namespace ContainerPftzv8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSyw5apService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PSyw5ap' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PSyw5ap'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contact' => ['privates', '.errored..service_locator.PSyw5ap.App\\Entity\\Contacts', NULL, 'Cannot autowire service ".service_locator.PSyw5ap": it references class "App\\Entity\\Contacts" but no such service exists.'],
        ], [
            'contact' => 'App\\Entity\\Contacts',
        ]);
    }
}
