<?php

namespace ContainerPftzv8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BHf1z3JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BHf1z3J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BHf1z3J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'target' => ['privates', '.errored..service_locator.BHf1z3J.App\\Entity\\Targets', NULL, 'Cannot autowire service ".service_locator.BHf1z3J": it references class "App\\Entity\\Targets" but no such service exists.'],
        ], [
            'target' => 'App\\Entity\\Targets',
        ]);
    }
}
