<?php

namespace ContainerPftzv8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddTargetTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddTargetType' shared autowired service.
     *
     * @return \App\Form\AddTargetType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddTargetType.php';

        return $container->privates['App\\Form\\AddTargetType'] = new \App\Form\AddTargetType();
    }
}
