<?php

namespace ContainerPftzv8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PSyw5ap.App\Entity\Contacts' shared service.
     *
     * @return \App\Entity\Contacts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PSyw5ap": it references class "App\\Entity\\Contacts" but no such service exists.');
    }
}
