<?php

namespace ContainerPftzv8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHideoutsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Bk4moDu.App\Entity\Hideouts' shared service.
     *
     * @return \App\Entity\Hideouts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Bk4moDu": it references class "App\\Entity\\Hideouts" but no such service exists.');
    }
}
