<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Y1lBL8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Y1lBL8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Y1lBL8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Y1lBL8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Y1lBL8\App_KernelDevDebugContainer([
    'container.build_hash' => '2Y1lBL8',
    'container.build_id' => '588e7927',
    'container.build_time' => 1616426537,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Y1lBL8');
