<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEIU7IKs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEIU7IKs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEIU7IKs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEIU7IKs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEIU7IKs\App_KernelDevDebugContainer([
    'container.build_hash' => 'EIU7IKs',
    'container.build_id' => 'e08d1a7a',
    'container.build_time' => 1616412292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEIU7IKs');
