<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPftzv8D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPftzv8D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPftzv8D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPftzv8D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPftzv8D\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pftzv8D',
    'container.build_id' => '887f65cb',
    'container.build_time' => 1616511047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPftzv8D');
