<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'agents_index' => [[], ['_controller' => 'App\\Controller\\AgentsController::index'], [], [['text', '/agents']], [], []],
    'agent_details' => [['id'], ['_controller' => 'App\\Controller\\AgentsController::showAgent'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/agents']], [], []],
    'contacts_index' => [[], ['_controller' => 'App\\Controller\\ContactsController::index'], [], [['text', '/contacts']], [], []],
    'contact_details' => [['id'], ['_controller' => 'App\\Controller\\ContactsController::showContact'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contacts']], [], []],
    'hideouts_index' => [[], ['_controller' => 'App\\Controller\\HideoutsController::index'], [], [['text', '/hideouts']], [], []],
    'hideout_details' => [['id'], ['_controller' => 'App\\Controller\\HideoutsController::showHideout'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/hideouts']], [], []],
    'app.home' => [[], ['_controller' => 'App\\Controller\\MissionsController::index'], [], [['text', '/']], [], []],
    'mission_details' => [['id'], ['_controller' => 'App\\Controller\\MissionsController::showMission'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/missions']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'skills_index' => [[], ['_controller' => 'App\\Controller\\SkillsController::index'], [], [['text', '/skills']], [], []],
    'skill_details' => [['id'], ['_controller' => 'App\\Controller\\SkillsController::showSkill'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/skills']], [], []],
    'targets_index' => [[], ['_controller' => 'App\\Controller\\TargetsController::index'], [], [['text', '/targets']], [], []],
    'target_details' => [['id'], ['_controller' => 'App\\Controller\\TargetsController::showAgent'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/targets']], [], []],
];
