<?php

namespace ContainerGPIYqS6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddMissionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddMissionType' shared autowired service.
     *
     * @return \App\Form\AddMissionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddMissionType.php';

        return $container->privates['App\\Form\\AddMissionType'] = new \App\Form\AddMissionType();
    }
}
