<?php

namespace ContainerGPIYqS6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTargetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BHf1z3J.App\Entity\Targets' shared service.
     *
     * @return \App\Entity\Targets
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BHf1z3J": it references class "App\\Entity\\Targets" but no such service exists.');
    }
}
