<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Missions extends \App\Entity\Missions implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'agents', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'skills', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'targets', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'endDate', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'hideouts'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'agents', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'skills', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'targets', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'endDate', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Missions' . "\0" . 'hideouts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Missions $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(string $country): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgents(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgents', []);

        return parent::getAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgent(\App\Entity\Agents $agent): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgent', [$agent]);

        return parent::addAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgent(\App\Entity\Agents $agent): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgent', [$agent]);

        return parent::removeAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkills(): ?\App\Entity\Skills
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkills', []);

        return parent::getSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkills(?\App\Entity\Skills $skills): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkills', [$skills]);

        return parent::setSkills($skills);
    }

    /**
     * {@inheritDoc}
     */
    public function getTargets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargets', []);

        return parent::getTargets();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarget(\App\Entity\Targets $target): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarget', [$target]);

        return parent::addTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTarget(\App\Entity\Targets $target): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTarget', [$target]);

        return parent::removeTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(string $startDate): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate(string $endDate): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$endDate]);

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\App\Entity\Contacts $contact): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', [$contact]);

        return parent::addContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\App\Entity\Contacts $contact): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', [$contact]);

        return parent::removeContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getHideouts(): ?\App\Entity\Hideouts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHideouts', []);

        return parent::getHideouts();
    }

    /**
     * {@inheritDoc}
     */
    public function setHideouts(?\App\Entity\Hideouts $hideouts): \App\Entity\Missions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHideouts', [$hideouts]);

        return parent::setHideouts($hideouts);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function areAgentNatAndTargetNatValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'areAgentNatAndTargetNatValid', []);

        return parent::areAgentNatAndTargetNatValid();
    }

    /**
     * {@inheritDoc}
     */
    public function areContactNatAndMissionCountryValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'areContactNatAndMissionCountryValid', []);

        return parent::areContactNatAndMissionCountryValid();
    }

    /**
     * {@inheritDoc}
     */
    public function areHideoutCountryAndMissionCountryValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'areHideoutCountryAndMissionCountryValid', []);

        return parent::areHideoutCountryAndMissionCountryValid();
    }

    /**
     * {@inheritDoc}
     */
    public function areMissionSkillAndAgentSkillValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'areMissionSkillAndAgentSkillValid', []);

        return parent::areMissionSkillAndAgentSkillValid();
    }

    /**
     * {@inheritDoc}
     */
    public function isMissionValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMissionValid', []);

        return parent::isMissionValid();
    }

}
